Fix ionCube Loader with PHP 8.0

diff --git a/php/fpm-loaders/Dockerfile b/php/fpm-loaders/Dockerfile
--- a/php/fpm-loaders/Dockerfile
+++ b/php/fpm-loaders/Dockerfile
@@ -24,20 +24,23 @@ RUN PHP_VERSION=$(php -v | head -n1 | cut -d' ' -f2 | cut -d. -f1-2) \
     && rm -rf /tmp/sourceguardian
 
 # Install and enable IonCube loader
+## IonCube doesn't support PHP 8.0: https://blog.ioncube.com/2022/08/12/ioncube-php-8-1-support-faq-were-almost-ready/
 RUN PHP_VERSION=$(php -v | head -n1 | cut -d' ' -f2 | cut -d. -f1-2) \
-    && if [ "$TARGETPLATFORM" = "linux/amd64" ]; then ICARCH=x86-64; \
-    elif [ "$TARGETPLATFORM" = "linux/arm64" ]; then ICARCH=aarch64; \
-    else ICARCH=x86-64; fi \
-    && mkdir -p /tmp/ioncube \
-    && cd /tmp/ioncube \
-    && curl -Os https://downloads.ioncube.com/loader_downloads/ioncube_loaders_lin_${ICARCH}.tar.gz \
-    && tar xzf ioncube_loaders_lin_${ICARCH}.tar.gz \
-    && IONCUBE_LOADER_PATH=ioncube/ioncube_loader_lin_${PHP_VERSION}.so \
-    && if [[ -f ${IONCUBE_LOADER_PATH} ]]; then \
-        cp ${IONCUBE_LOADER_PATH} "$(php -i | grep '^extension_dir =' | cut -d' ' -f3)/ioncube_loader.so" \
-            && echo "zend_extension=ioncube_loader.so" > /etc/php.d/01-ioncube-loader.ini; \
-    else \
-        >&2 printf "\033[33mWARNING\033[0m: IonCube loaders for PHP_VERSION %s could not be found at %s\n" \
-            "${PHP_VERSION}" "${IONCUBE_LOADER_PATH}"; \
-    fi \
-    && rm -rf /tmp/ioncube
+    && if [[ "${PHP_VERSION}" != "8.0" ]]; then \
+        && if [ "$TARGETPLATFORM" = "linux/amd64" ]; then ICARCH=x86-64; \
+        elif [ "$TARGETPLATFORM" = "linux/arm64" ]; then ICARCH=aarch64; \
+        else ICARCH=x86-64; fi \
+        && mkdir -p /tmp/ioncube \
+        && cd /tmp/ioncube \
+        && curl -Os https://downloads.ioncube.com/loader_downloads/ioncube_loaders_lin_${ICARCH}.tar.gz \
+        && tar xzf ioncube_loaders_lin_${ICARCH}.tar.gz \
+        && IONCUBE_LOADER_PATH=ioncube/ioncube_loader_lin_${PHP_VERSION}.so \
+        && if [[ -f ${IONCUBE_LOADER_PATH} ]]; then \
+            cp ${IONCUBE_LOADER_PATH} "$(php -i | grep '^extension_dir =' | cut -d' ' -f3)/ioncube_loader.so" \
+                && echo "zend_extension=ioncube_loader.so" > /etc/php.d/01-ioncube-loader.ini; \
+        else \
+            >&2 printf "\033[33mWARNING\033[0m: IonCube loaders for PHP_VERSION %s could not be found at %s\n" \
+                "${PHP_VERSION}" "${IONCUBE_LOADER_PATH}"; \
+        fi \
+        && rm -rf /tmp/ioncube \
+    fi
